"""xAI Grok Imagine image provider (opt-in).

Uses the OpenAI-compatible Images API at ``https://api.x.ai/v1`` over HTTPS
+ ``requests`` — the same pattern as the OpenAI image provider, no extra SDK.
Credentials come from an environment variable (default ``XAI_API_KEY``),
never from YAML.

Text-to-image uses ``POST /v1/images/generations`` with ``model``,
``prompt``, ``n``, ``aspect_ratio``, ``resolution``, and
``response_format=b64_json``. Generated bytes are cover-cropped to the
pipeline canvas and written as PNG.

Official xAI image editing (``POST /v1/images/edits``) accepts a public URL,
a base64 data URI, or a Files API ``file_id``. Multi-image edits take up to
three sources via ``images: [{file_id|url}, ...]``.

Approved Biscuit reference assets are uploaded once with ``POST /v1/files``
and then sent as ``file_id`` values. Local-path data-URI edits remain
available for documented Imagine 2.x models. Text-only generation is
unchanged when a request has no references.
"""

from __future__ import annotations

import base64
import io
import logging
import time
from pathlib import Path
from typing import Any

from PIL import Image

from biscuit.config import XAIImageConfig
from biscuit.exceptions import ImageGenerationError
from biscuit.image_ops import fit_cover
from biscuit.providers.base import ImageProvider, ImageRequest
from biscuit.providers.registry import image_registry

logger = logging.getLogger(__name__)

_RETRY_STATUSES = frozenset({429, 500, 502, 503, 504})
_DEFAULT_BASE_URL = "https://api.x.ai/v1"


def xai_model_supports_image_edits(model: str) -> bool:
    """Return whether official xAI docs document an edits API for this model."""

    return str(model).lower().startswith("grok-imagine-image-2")


@image_registry.register("xai")
class XAIImageProvider(ImageProvider):
    def __init__(self, xai: XAIImageConfig | None = None, **_ignored: object) -> None:
        self._config = xai or XAIImageConfig()

    def generate(self, request: ImageRequest, output_path: Path) -> Path:
        api_key = self._config.resolve_api_key(required=True)
        assert api_key is not None

        scene_label = f"{request.scene.id} (scene {request.scene.index:03d})"
        file_ids = [
            ref.provider_file_id
            for ref in request.references
            if getattr(ref, "provider_file_id", "")
        ][:3]
        local_refs = [ref for ref in request.references if ref.path.exists() and ref.path.is_file()]
        use_file_ids = bool(file_ids)
        use_local_edits = (
            (not use_file_ids)
            and bool(local_refs)
            and xai_model_supports_image_edits(self._config.model)
        )
        if local_refs and not use_file_ids and not use_local_edits:
            logger.info(
                "xAI model %s has no documented local-path image-edit path; "
                "ignoring %d reference file(s) for %s",
                self._config.model,
                len(local_refs),
                scene_label,
            )
        use_edits = use_file_ids or use_local_edits
        logger.info(
            "Generating image %03d with xAI / %s%s",
            request.scene.index,
            self._config.model,
            " (image edit)" if use_edits else "",
        )

        started = time.monotonic()
        payload = self._request_image(
            api_key=api_key,
            prompt=request.prompt,
            scene_label=scene_label,
            reference_file_ids=file_ids if use_file_ids else None,
            reference_paths=[ref.path for ref in local_refs[:3]] if use_local_edits else None,
        )
        elapsed = time.monotonic() - started
        image_bytes = _decode_image_bytes(payload, scene_label)
        logger.info("Generated %s in %.1fs", scene_label, elapsed)

        revised = _revised_prompt(payload)
        if revised:
            _write_revised_prompt(output_path, request.scene.index, revised)

        _save_fitted_png(image_bytes, output_path, request.width, request.height, scene_label)
        return output_path

    def _generations_url(self) -> str:
        base = (self._config.base_url or _DEFAULT_BASE_URL).rstrip("/")
        return f"{base}/images/generations"

    def _edits_url(self) -> str:
        base = (self._config.base_url or _DEFAULT_BASE_URL).rstrip("/")
        return f"{base}/images/edits"

    def _files_url(self) -> str:
        base = (self._config.base_url or _DEFAULT_BASE_URL).rstrip("/")
        return f"{base}/files"

    def upload_reference(self, path: Path) -> str:
        """Upload a local image to the xAI Files API and return its ``file_id``."""

        if not path.exists() or not path.is_file():
            raise ImageGenerationError(f"Cannot upload missing reference image: {path}")
        api_key = self._config.resolve_api_key(required=True)
        assert api_key is not None
        import requests

        headers = {"Authorization": f"Bearer {api_key}"}
        last_error: Exception | None = None
        attempts = self._config.max_retries + 1
        for attempt in range(1, attempts + 1):
            try:
                with path.open("rb") as fh:
                    response = requests.post(
                        self._files_url(),
                        headers=headers,
                        files={"file": (path.name, fh, "application/octet-stream")},
                        data={"purpose": "assistants"},
                        timeout=self._config.timeout_seconds,
                    )
            except requests.RequestException as exc:
                last_error = exc
                if attempt < attempts:
                    logger.warning(
                        "xAI file upload error for %s (attempt %d/%d): %s; retrying.",
                        path.name,
                        attempt,
                        attempts,
                        exc,
                    )
                    time.sleep(min(2 ** (attempt - 1), 8))
                    continue
                raise ImageGenerationError(f"xAI file upload failed for {path.name}: {exc}") from exc
            if response.status_code in _RETRY_STATUSES and attempt < attempts:
                time.sleep(min(2 ** (attempt - 1), 8))
                continue
            if response.status_code >= 400:
                raise ImageGenerationError(
                    f"xAI file upload failed for {path.name}: "
                    f"HTTP {response.status_code} {_safe_error_text(response)}"
                )
            try:
                payload = response.json()
            except Exception as exc:  # noqa: BLE001
                raise ImageGenerationError(
                    f"xAI file upload failed for {path.name}: response was not JSON."
                ) from exc
            file_id = str((payload or {}).get("id") or "").strip()
            if not file_id:
                raise ImageGenerationError(
                    f"xAI file upload for {path.name} did not return a file id."
                )
            logger.info("Uploaded reference %s to xAI files as %s", path.name, file_id)
            return file_id
        raise ImageGenerationError(f"xAI file upload failed for {path.name}: {last_error}")

    def _request_image(
        self,
        *,
        api_key: str,
        prompt: str,
        scene_label: str,
        reference_file_ids: list[str] | None = None,
        reference_paths: list[Path] | None = None,
        reference_path: Path | None = None,
    ) -> dict[str, Any]:
        import requests

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        body: dict[str, Any] = {
            "model": self._config.model,
            "prompt": prompt,
            "n": 1,
            "aspect_ratio": self._config.aspect_ratio,
            "resolution": self._config.resolution,
            "response_format": "b64_json",
        }
        url = self._generations_url()
        file_ids = [item for item in (reference_file_ids or []) if item][:3]
        paths = list(reference_paths or [])
        if reference_path is not None:
            paths = [reference_path, *paths]
        paths = paths[:3]
        if file_ids:
            url = self._edits_url()
            if len(file_ids) == 1:
                body["image"] = {"file_id": file_ids[0]}
            else:
                body["images"] = [{"file_id": item} for item in file_ids]
        elif paths:
            url = self._edits_url()
            if len(paths) == 1:
                body["image"] = {"url": _png_data_uri(paths[0]), "type": "image_url"}
            else:
                body["images"] = [{"url": _png_data_uri(path), "type": "image_url"} for path in paths]
        last_error: Exception | None = None
        attempts = self._config.max_retries + 1
        for attempt in range(1, attempts + 1):
            try:
                response = requests.post(
                    url,
                    headers=headers,
                    json=body,
                    timeout=self._config.timeout_seconds,
                )
            except requests.RequestException as exc:
                last_error = exc
                if attempt < attempts:
                    logger.warning(
                        "xAI request error for %s (attempt %d/%d): %s; retrying.",
                        scene_label,
                        attempt,
                        attempts,
                        exc,
                    )
                    time.sleep(min(2 ** (attempt - 1), 8))
                    continue
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: {exc}"
                ) from exc

            if response.status_code in _RETRY_STATUSES and attempt < attempts:
                logger.warning(
                    "Transient xAI error for %s (HTTP %s, attempt %d/%d); retrying.",
                    scene_label,
                    response.status_code,
                    attempt,
                    attempts,
                )
                time.sleep(min(2 ** (attempt - 1), 8))
                continue
            if response.status_code >= 400:
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: "
                    f"HTTP {response.status_code} {_safe_error_text(response)}"
                )
            try:
                payload = response.json()
            except Exception as exc:  # noqa: BLE001
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: response was not JSON."
                ) from exc
            if not isinstance(payload, dict):
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: unexpected JSON payload."
                )
            return payload
        raise ImageGenerationError(f"xAI image generation failed for {scene_label}: {last_error}")


def _png_data_uri(path: Path) -> str:
    payload = base64.b64encode(path.read_bytes()).decode("ascii")
    return f"data:image/png;base64,{payload}"


def _decode_image_bytes(payload: dict[str, Any], scene_label: str) -> bytes:
    data = payload.get("data")
    if not isinstance(data, list) or not data:
        raise ImageGenerationError(f"xAI response for {scene_label} had no image data.")
    first = data[0] if isinstance(data[0], dict) else {}
    b64 = first.get("b64_json")
    if not b64:
        raise ImageGenerationError(
            f"xAI response for {scene_label} did not include b64_json image bytes."
        )
    try:
        return base64.b64decode(b64)
    except Exception as exc:  # noqa: BLE001
        raise ImageGenerationError(f"xAI image for {scene_label} was not valid base64.") from exc


def _revised_prompt(payload: dict[str, Any]) -> str | None:
    data = payload.get("data")
    if not isinstance(data, list) or not data or not isinstance(data[0], dict):
        return None
    revised = data[0].get("revised_prompt")
    return str(revised) if revised else None


def _write_revised_prompt(output_path: Path, index: int, text: str) -> None:
    prompts_dir = output_path.parent.parent / "image_prompts"
    if not prompts_dir.is_dir():
        return
    path = prompts_dir / f"{index:03d}.revised.txt"
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    logger.info("Wrote API revised prompt to %s", path)


def _save_fitted_png(
    image_bytes: bytes,
    output_path: Path,
    width: int,
    height: int,
    scene_label: str,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_name(output_path.name + ".partial")
    try:
        with Image.open(io.BytesIO(image_bytes)) as raw:
            fitted = fit_cover(raw, width, height)
            fitted.save(tmp_path, format="PNG")
        tmp_path.replace(output_path)
    except ImageGenerationError:
        raise
    except Exception as exc:  # noqa: BLE001
        raise ImageGenerationError(f"Could not decode/fit xAI image for {scene_label}: {exc}") from exc
    finally:
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


def _safe_error_text(response: Any) -> str:
    try:
        payload = response.json()
        error = payload.get("error") if isinstance(payload, dict) else None
        if isinstance(error, dict):
            message = str(error.get("message") or error.get("code") or "")
            code = error.get("code")
            if code and message:
                return f"{code}: {message}"[:500]
            return (message or str(error))[:500]
        if isinstance(error, str) and error:
            return error[:500]
        return str(payload)[:500]
    except Exception:  # noqa: BLE001
        return (getattr(response, "text", "") or "")[:500]
