"""xAI Grok Imagine image provider (opt-in).

Uses the OpenAI-compatible Images API at ``https://api.x.ai/v1`` over HTTPS
+ ``requests`` — the same pattern as the OpenAI image provider, no extra SDK.
Credentials come from an environment variable (default ``XAI_API_KEY``),
never from YAML.

Text-to-image uses ``POST /v1/images/generations`` with ``model``,
``prompt``, ``n``, ``aspect_ratio``, ``resolution``, and
``response_format=b64_json``. Generated bytes are cover-cropped to the
pipeline canvas and written as PNG. Character-reference edits are not
implemented here; existing scene prompts are sent unchanged.
"""

from __future__ import annotations

import base64
import io
import logging
import time
from pathlib import Path
from typing import Any

from PIL import Image

from biscuit.config import XAIImageConfig
from biscuit.exceptions import ImageGenerationError
from biscuit.image_ops import fit_cover
from biscuit.providers.base import ImageProvider, ImageRequest
from biscuit.providers.registry import image_registry

logger = logging.getLogger(__name__)

_RETRY_STATUSES = frozenset({429, 500, 502, 503, 504})
_DEFAULT_BASE_URL = "https://api.x.ai/v1"


@image_registry.register("xai")
class XAIImageProvider(ImageProvider):
    def __init__(self, xai: XAIImageConfig | None = None, **_ignored: object) -> None:
        self._config = xai or XAIImageConfig()

    def generate(self, request: ImageRequest, output_path: Path) -> Path:
        api_key = self._config.resolve_api_key(required=True)
        assert api_key is not None

        scene_label = f"{request.scene.id} (scene {request.scene.index:03d})"
        logger.info(
            "Generating image %03d with xAI / %s",
            request.scene.index,
            self._config.model,
        )
        logger.debug(
            "xAI prompt for %s (%d chars):\n%s",
            scene_label,
            len(request.prompt),
            request.prompt,
        )
        if request.references:
            logger.info(
                "xAI text-to-image ignores %d character reference file(s) for %s",
                len(request.references),
                scene_label,
            )

        started = time.monotonic()
        payload = self._request_image(
            api_key=api_key,
            prompt=request.prompt,
            scene_label=scene_label,
        )
        elapsed = time.monotonic() - started
        image_bytes = _decode_image_bytes(payload, scene_label)
        logger.info("Generated %s in %.1fs", scene_label, elapsed)

        revised = _revised_prompt(payload)
        if revised:
            _write_revised_prompt(output_path, request.scene.index, revised)

        _save_fitted_png(image_bytes, output_path, request.width, request.height, scene_label)
        return output_path

    def _generations_url(self) -> str:
        base = (self._config.base_url or _DEFAULT_BASE_URL).rstrip("/")
        return f"{base}/images/generations"

    def _request_image(self, *, api_key: str, prompt: str, scene_label: str) -> dict[str, Any]:
        import requests

        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        }
        body = {
            "model": self._config.model,
            "prompt": prompt,
            "n": 1,
            "aspect_ratio": self._config.aspect_ratio,
            "resolution": self._config.resolution,
            "response_format": "b64_json",
        }
        last_error: Exception | None = None
        attempts = self._config.max_retries + 1
        for attempt in range(1, attempts + 1):
            try:
                response = requests.post(
                    self._generations_url(),
                    headers=headers,
                    json=body,
                    timeout=self._config.timeout_seconds,
                )
            except requests.RequestException as exc:
                last_error = exc
                if attempt < attempts:
                    logger.warning(
                        "xAI request error for %s (attempt %d/%d): %s; retrying.",
                        scene_label,
                        attempt,
                        attempts,
                        exc,
                    )
                    time.sleep(min(2 ** (attempt - 1), 8))
                    continue
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: {exc}"
                ) from exc

            if response.status_code in _RETRY_STATUSES and attempt < attempts:
                logger.warning(
                    "Transient xAI error for %s (HTTP %s, attempt %d/%d); retrying.",
                    scene_label,
                    response.status_code,
                    attempt,
                    attempts,
                )
                time.sleep(min(2 ** (attempt - 1), 8))
                continue
            if response.status_code >= 400:
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: "
                    f"HTTP {response.status_code} {_safe_error_text(response)}"
                )
            try:
                payload = response.json()
            except Exception as exc:  # noqa: BLE001
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: response was not JSON."
                ) from exc
            if not isinstance(payload, dict):
                raise ImageGenerationError(
                    f"xAI image generation failed for {scene_label}: unexpected JSON payload."
                )
            return payload
        raise ImageGenerationError(f"xAI image generation failed for {scene_label}: {last_error}")


def _decode_image_bytes(payload: dict[str, Any], scene_label: str) -> bytes:
    data = payload.get("data")
    if not isinstance(data, list) or not data:
        raise ImageGenerationError(f"xAI response for {scene_label} had no image data.")
    first = data[0] if isinstance(data[0], dict) else {}
    b64 = first.get("b64_json")
    if not b64:
        raise ImageGenerationError(
            f"xAI response for {scene_label} did not include b64_json image bytes."
        )
    try:
        return base64.b64decode(b64)
    except Exception as exc:  # noqa: BLE001
        raise ImageGenerationError(f"xAI image for {scene_label} was not valid base64.") from exc


def _revised_prompt(payload: dict[str, Any]) -> str | None:
    data = payload.get("data")
    if not isinstance(data, list) or not data or not isinstance(data[0], dict):
        return None
    revised = data[0].get("revised_prompt")
    return str(revised) if revised else None


def _write_revised_prompt(output_path: Path, index: int, text: str) -> None:
    prompts_dir = output_path.parent.parent / "image_prompts"
    if not prompts_dir.is_dir():
        return
    path = prompts_dir / f"{index:03d}.revised.txt"
    path.write_text(text.rstrip() + "\n", encoding="utf-8")
    logger.info("Wrote API revised prompt to %s", path)


def _save_fitted_png(
    image_bytes: bytes,
    output_path: Path,
    width: int,
    height: int,
    scene_label: str,
) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = output_path.with_name(output_path.name + ".partial")
    try:
        with Image.open(io.BytesIO(image_bytes)) as raw:
            fitted = fit_cover(raw, width, height)
            fitted.save(tmp_path, format="PNG")
        tmp_path.replace(output_path)
    except ImageGenerationError:
        raise
    except Exception as exc:  # noqa: BLE001
        raise ImageGenerationError(f"Could not decode/fit xAI image for {scene_label}: {exc}") from exc
    finally:
        if tmp_path.exists():
            tmp_path.unlink(missing_ok=True)


def _safe_error_text(response: Any) -> str:
    try:
        payload = response.json()
        error = payload.get("error") if isinstance(payload, dict) else None
        if isinstance(error, dict):
            message = str(error.get("message") or error.get("code") or "")
            code = error.get("code")
            if code and message:
                return f"{code}: {message}"[:500]
            return (message or str(error))[:500]
        if isinstance(error, str) and error:
            return error[:500]
        return str(payload)[:500]
    except Exception:  # noqa: BLE001
        return (getattr(response, "text", "") or "")[:500]
